schema: "classroom50/repo-config/v1"
classroom: "agi"
assignment: "todo"
owner:
  username: "xaeoon"
  id: 206808571
  accepted_at: "2026-09-08T23:53:08Z"
source:
  owner: "gsm-class"
  owner_id: 318515310
  repo: "todo"
  branch: "main"
